### ISSUE TITLE
Fix GCC 14 rejection of menu callback returns

### ISSUE THREAD

**Issue by laqieer** [laqieer/fireemblem8-expansion#197]
## Bug triage

**Classification:** Confirmed build regression.

The supported modern release build fails with GCC 14.2.1 because `src/bmmenu.c` contains non-void menu callbacks that either use `return;` or fall through without returning a value. `-Werror` turns the explicit return mismatch into a hard build failure.

## Contract

- Scope: return the neutral callback value `0` from the affected draw, switch, and help callbacks.
- Non-goals: no menu behavior, ABI, feature profile, save format, generated data, localization, or archival-lane changes.
- Dependencies: existing `MenuItemDef` callback signatures in `include/uimenu.h`.
- Dependents: steal-item and item-menu callback tables in `src/menu_def.c`.
- Conflicts: none.
- Rollback: revert the callback return commit if post-merge Build CI regresses.

## Tester-facing case

**TC-BUILD-GCC14-MENU-RETURN-001**

- Profile/artifact: modern release, AAPCS, `build/expansion-modern/release/aapcs/fireemblem8.gba`.
- Environment: Ubuntu package toolchain, `arm-none-eabi-gcc` 14.2.1.
- Prerequisite: clean or incremental checkout with modern quickstart dependencies installed.
- Action: run `./scripts/quickstart.sh` or `make expansion-modern-boot-check MODERN_CONFIG=release MODERN_ABI=aapcs`.
- Expected: compilation, link, and boot verification succeed.
- Negative control: before the fix, GCC reports `return with no value, in function returning non-void` in `StealItemMenuCommand_Draw` and `ItemMenu_SwitchOut_DoNothing`.
- Interactions/save compatibility: none; callbacks retain the intended neutral result and no persistent data changes.
- Automation: the modern release boot-check exercises compile, link, ROM generation, and deterministic boot verification.

**Comment by laqieer** [comment]
Post-merge hold: PR #198 merged as `cc7dcab31cac4ebef0e05e0e20211c22dbb2c0d8`. Exact-master Build [33886934525](https://github.com/laqieer/fireemblem8-expansion/actions/runs/33886934525) passed host tests, modern builds, extended-host tests, and the archival lane, but failed the master-only `patch-release` job at the same pre-existing `stage=isolated exit=1` boundary tracked by #177 and fix-forward PR #195. The issue remains open until a consolidated Build succeeds on the resulting master revision and `make remote-completion-check` passes.

**Comment by laqieer** [comment]
The owner-context failed-job rerun of exact-master Build [33886934525](https://github.com/laqieer/fireemblem8-expansion/actions/runs/33886934525) reproduced the same pre-existing publisher failure: `patch-release` ended at `stage=isolated exit=1`, while `host-tests`, `build`, `extended-host-tests`, and `legacy` all succeeded again. Repeated reruns cannot satisfy the gate without the #177 fix-forward in PR #195. #197 remains open, and `make remote-completion-check` is intentionally not run until a consolidated Build succeeds on the resulting master revision.

**Comment by laqieer** [comment]
## Delivered: defined modern menu callback returns

The confirmed GCC14 regression was fixed in PR #198, merged as
`cc7dcab31cac4ebef0e05e0e20211c22dbb2c0d8`. Four non-void callbacks return
neutral0 for modern builds; `FE8_ARCHIVAL_BUILD` retains the original archival
source behavior. No menu rules, ABI, resource, save/config or localization
change.

`TC-BUILD-GCC14-MENU-RETURN-001` was exercised with actual
`arm-none-eabi-gcc`14.2.1: the pre-fix valueless-return compilation failed;
modern release AAPCS compile/link/boot and the guarded explicit archival build
passed. Exact commands/tool details remain in
[PR198 evidence](https://github.com/laqieer/fireemblem8-expansion/pull/198#issuecomment-5541236039):
GCC14.2.1, gdb-multiarch17.1, mGBA0.10.5 and the recorded archival compilers.
No new tool or broad local build was needed for this final closure.

Candidate ebc8ec7 passed Build33881899477 and clean review33881907143.
The independent-root preflight was3 files,+101/-4=105 changed lines.
The earlier master failures were solely the old publisher, not a compiler
regression.

Git ancestry confirms cc7 is contained in current master
`497a9969c0731302cee22aafc454b75bb18f7f8b`. Its complete automatic
[Build34028587814](https://github.com/laqieer/fireemblem8-expansion/actions/runs/34028587814)
and CodeQL34028587603 succeeded, including real patch publication after #219.
`make remote-completion-check` passed on that clean exact master/upstream.
The publisher hold is cleared; closing #197.
